### ISSUE TITLE
queueTrigger event changing during timeout

### ISSUE THREAD

**Issue by kofifus** [omriyariv/jquery-singleclick#1]
Hi Omri and thanks for a great plugin

queueTrigger creates buggy behavior if the bubbling of the event changes the event object. I've seen cases where by the time the timout body(https://github.com/omriyariv/jquery-singleclick/blob/master/jquery.singleclick.js#L55) is called, event.target for example is different than for the orignal event, causing singleClick to be sent to a different element (ie the div behind the element).

I solved this by creating a copy of the event object like this:

```
        queueTrigger: function($el, event, args) {
            // Queue a trigger function.
            let orgEvent=$.Event(event.type, event); // create a duplicate of the event 
            let timeout = setTimeout(function() {
                // Before applying the handler, we change the type of the
                // standard 'click' event to 'singleclick'.
                orgEvent.type = orgEvent.handleObj.origType;
                orgEvent.handleObj.handler.apply($el, args);
                // After calling the handler we recover the original type
                // to try to avoid unexpected behavior of other handlers
                // that might be holding a reference to the event object.
                orgEvent.type = orgEvent.handleObj.type;
                // If the queued event fired successfully, we remove the variable
                // referencing the timeout to indicate 'no more pending triggers'.
                $el.removeData(singleclick.dataProp);
            }, singleclick.timeout);
            // Save a reference to the queued trigger function.
            $el.data(singleclick.dataProp, timeout);
        },

```

hope this helps

**Comment by omriyariv** [comment]
Hi kofifus, thanks for this helpful feedback. I'll integrate your fix soon. Could you maybe provide instructions for reproducing this so I can make sure it's fixed correctly? I cannot think of a simple scenario in which `event.target` changes (unless you're using React?)

**Comment by kofifus** [comment]
hmmm .. unfortunately I can't. It is a complicated scenario and part of a big codebase and making a sample can take too much time. Basically I had a jstree on top of a div with both the jstree elem and the div elem having click/singleclick events. When a click was initiated by a tap on one of the tree nodes on a mobile (or chrome mobile emulator) the singleclick event ended up in the div behind the tree and not the tree. On the desktop it works fine so it is possibly a chrome on mobile bug.

In the debugger I could see the event target changing during the timeout which caused the bug, the code I posted made sure the event stays the same.

Hope this helps/
